name: Open Data Access Tools for OEDI
on:
  push:
    branches:
    - release
  pull_request:
    branches:
    - release

jobs:
  release:
    name: Deploy OEDI data lake
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        python-version: [3.9]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Config AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ secrets.AWS_REGION_NAME }}
        role-to-assume: ${{ secrets.AWS_IAM_ROLE_TO_ASSUME }}
    - name: CDK List
      uses: youyo/aws-cdk-github-actions@v2
      with:
        cdk_subcommand: "list"
        actions_comment: true
